server:
  port: 8070
  servlet:
    context-path: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: bc-govern-gateway

zuul:
  routes:
    adjsut-server:
      path: /adjust/**  #注意字母使用大写无效
      serviceId: bc-service-adjust #微服务名称，网关会从eureka中获取该服务名称下的服务实例的地址
      strip-prefix: false #true：代理转发时去掉前缀，false:代理转发时不去掉前缀
      sensitiveHeaders:  #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务
      ignoredHeaders:  #默认为空表示不过虑任何头
    login-server:
      path: /adjust/**
      serviceId: bc-service-login
      strip-prefix: false
      sensitiveHeaders:  #
      ignoredHeaders:  #

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
