spring:
  application:
    name: bc-service-adjust
  datasource:
    username: root
    password: W_y1:478!
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://103.44.30.46:3306/siemReap?characterEncoding=utf8
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1

  redis:
    host: 103.44.30.46
    port: 6379
    password: W_y1:478!
#  redis:
#    #数据库索引
#    database: 0
#    host: 103.44.30.46
#    port: 6379
#    password: W_y1:478!
#    jedis:
#      pool:
#        #最大连接数
#        max-active: 8
#        #最大阻塞等待时间(负数表示没限制)
#        max-wait: -1
#        #最大空闲
#        max-idle: 8
#        #最小空闲
#        min-idle: 0
#    #连接超时时间
#    timeout: 10000


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
