spring:
  application:
    name: bc-service-login

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: BcWebApp
  clientSecret: BcWebApp
  cookieDomain: bc.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/bc.keystore
    secret: bckeystore
    alias: bckey
    password: bc9527
authParams:
  loginReturnType: JSON